### ISSUE TITLE
Issue with get_var_flanks.py

### ISSUE THREAD

**Issue by DM2016** [NCBI-Hackathons/PSST#3]
Using the below command, the following error is generated:

python get_var_flanks.py -i gene_snp_accessions.txt -e email@account.com -o gene_snp_flanks.txt

where gene_snp_accessions.txt contains the SNP names from gene (0.01 <= MAF <= 0.5)

email@account.com is the email

and gene_SNP_flanks.txt is the output.

Traceback (most recent call last):
  File "get_var_flanks.py", line 86, in <module>
    main(sys.argv)
  File "get_var_flanks.py", line 82, in main
    flanking_sequences = get_var_flanking_sequences(accessions,email)
  File "get_var_flanks.py", line 12, in get_var_flanking_sequences
    for record in records:
  File "/home/moralesdia/.local/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 286, in parse
    self.parser.Parse(text, False)
  File "/home/moralesdia/.local/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 390, in endElementHandler
    raise RuntimeError(value)
RuntimeError: Invalid uid rs1010447 at position=0

To fix this problem, the input snp files need to have the 'rs', removed.

**Comment by sean-la** [comment]
I modified `get_var_flanks.py` to remove `rs` from the beginning of accessions if it exists. Thanks Diego!

**Comment by DM2016** [comment]
Thank you very much Sean!


________________________________
